import type { ActivityEntry, Notification, WorkspaceMember } from "@/types";

import { ago } from "./clock";

export const mockActivity: ActivityEntry[] = [
  {
    id: "act_01",
    kind: "experiment",
    title: "Revenue QA finished",
    description: "240 samples · faithfulness 0.914 · +2.1% vs. previous run",
    actor: "Himanshu Rao",
    createdAt: ago({ hours: 2 }),
    status: "completed",
  },
  {
    id: "act_02",
    kind: "experiment",
    title: "RAG Benchmark started",
    description: "HyDE over Engineering Docs · 512 samples",
    actor: "Priya Nair",
    createdAt: ago({ hours: 4 }),
    status: "running",
  },
  {
    id: "act_03",
    kind: "dataset",
    title: "Engineering Docs re-indexing",
    description: "12,940 chunks · text-embedding-3-large · 38% complete",
    actor: "System",
    createdAt: ago({ minutes: 38 }),
    status: "indexing",
  },
  {
    id: "act_04",
    kind: "provider",
    title: "Ollama connection failed",
    description: "Dial tcp 127.0.0.1:11434: connect: connection refused",
    actor: "System",
    createdAt: ago({ minutes: 38 }),
    status: "error",
  },
  {
    id: "act_05",
    kind: "experiment",
    title: "Support QA failed",
    description: "Aborted at sample 102 · context recall below threshold",
    actor: "Himanshu Rao",
    createdAt: ago({ hours: 20 }),
    status: "failed",
  },
  {
    id: "act_06",
    kind: "pipeline",
    title: "Hybrid + Rerank promoted",
    description: "Set as the workspace default pipeline",
    actor: "Dana Okafor",
    createdAt: ago({ days: 1, hours: 1 }),
  },
  {
    id: "act_07",
    kind: "dataset",
    title: "Legal Contracts index failed",
    description: "Malformed PDF in vendor-terms-v3.pdf · 3 documents skipped",
    actor: "System",
    createdAt: ago({ days: 3, hours: 8 }),
    status: "failed",
  },
  {
    id: "act_08",
    kind: "experiment",
    title: "Reranker Ablation finished",
    description: "240 samples · context precision 0.948",
    actor: "Himanshu Rao",
    createdAt: ago({ days: 4, hours: 9 }),
    status: "completed",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "ntf_01",
    title: "RAG Benchmark is 62% complete",
    description: "512 samples across Engineering Docs. Estimated 9 minutes remaining.",
    createdAt: ago({ minutes: 3 }),
    read: false,
    tone: "info",
  },
  {
    id: "ntf_02",
    title: "Ollama is unreachable",
    description: "The self-hosted endpoint refused the last 4 connections.",
    createdAt: ago({ minutes: 38 }),
    read: false,
    tone: "danger",
  },
  {
    id: "ntf_03",
    title: "Revenue QA completed",
    description: "Faithfulness improved 2.1 points over the previous run.",
    createdAt: ago({ hours: 2 }),
    read: false,
    tone: "success",
  },
  {
    id: "ntf_04",
    title: "Finance Reports index is stale",
    description: "Two documents were updated after the last embedding run.",
    createdAt: ago({ hours: 6 }),
    read: true,
    tone: "warning",
  },
  {
    id: "ntf_05",
    title: "Multi Query Sweep queued",
    description: "Waiting for a free experiment worker.",
    createdAt: ago({ minutes: 22 }),
    read: true,
    tone: "info",
  },
];

export const mockMembers: WorkspaceMember[] = [
  {
    id: "usr_01",
    name: "Himanshu Rao",
    email: "himanshu@acme.dev",
    role: "Owner",
    initials: "HR",
    lastActiveAt: ago({ minutes: 2 }),
  },
  {
    id: "usr_02",
    name: "Priya Nair",
    email: "priya@acme.dev",
    role: "Admin",
    initials: "PN",
    lastActiveAt: ago({ minutes: 26 }),
  },
  {
    id: "usr_03",
    name: "Dana Okafor",
    email: "dana@acme.dev",
    role: "Member",
    initials: "DO",
    lastActiveAt: ago({ hours: 5 }),
  },
  {
    id: "usr_04",
    name: "Marco Silveira",
    email: "marco@acme.dev",
    role: "Viewer",
    initials: "MS",
    lastActiveAt: ago({ days: 2, hours: 3 }),
  },
];
