import type { Model, Provider } from "@/types";

import { ago } from "./clock";

export const mockProviders: Provider[] = [
  {
    id: "openai",
    name: "OpenAI",
    description: "Frontier chat, reasoning and embedding models.",
    status: "connected",
    modelCount: 5,
    baseUrl: "https://api.openai.com/v1",
    apiKeyConfigured: true,
    apiKeyHint: "sk-proj-…9a91",
    lastCheckedAt: ago({ minutes: 4 }),
    docsUrl: "https://platform.openai.com/docs",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    description: "Claude models for long-context generation and analysis.",
    status: "connected",
    modelCount: 3,
    baseUrl: "https://api.anthropic.com/v1",
    apiKeyConfigured: true,
    apiKeyHint: "sk-ant-…41c7",
    lastCheckedAt: ago({ minutes: 4 }),
    docsUrl: "https://docs.anthropic.com",
  },
  {
    id: "google",
    name: "Google",
    description: "Gemini models and the text-embedding family.",
    status: "connected",
    modelCount: 3,
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    apiKeyConfigured: true,
    apiKeyHint: "AIza…7f2e",
    lastCheckedAt: ago({ minutes: 12 }),
    docsUrl: "https://ai.google.dev/gemini-api/docs",
  },
  {
    id: "ollama",
    name: "Ollama",
    description: "Self-hosted inference for open-weight models and rerankers.",
    status: "error",
    modelCount: 4,
    baseUrl: "http://localhost:11434",
    apiKeyConfigured: false,
    lastCheckedAt: ago({ minutes: 38 }),
    docsUrl: "https://github.com/ollama/ollama",
  },
];

export const mockModels: Model[] = [
  {
    id: "gpt-4.1",
    name: "gpt-4.1",
    providerId: "openai",
    providerName: "OpenAI",
    kind: "chat",
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
    inputCostPerMillion: 2,
    outputCostPerMillion: 8,
    capabilities: ["chat", "vision", "tools", "json", "reasoning"],
    status: "healthy",
    releasedAt: ago({ days: 164 }),
  },
  {
    id: "gpt-4.1-mini",
    name: "gpt-4.1-mini",
    providerId: "openai",
    providerName: "OpenAI",
    kind: "chat",
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
    inputCostPerMillion: 0.4,
    outputCostPerMillion: 1.6,
    capabilities: ["chat", "vision", "tools", "json"],
    status: "healthy",
    releasedAt: ago({ days: 164 }),
  },
  {
    id: "gpt-4o",
    name: "gpt-4o",
    providerId: "openai",
    providerName: "OpenAI",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    inputCostPerMillion: 2.5,
    outputCostPerMillion: 10,
    capabilities: ["chat", "vision", "tools", "json"],
    status: "healthy",
    releasedAt: ago({ days: 428 }),
  },
  {
    id: "text-embedding-3-large",
    name: "text-embedding-3-large",
    providerId: "openai",
    providerName: "OpenAI",
    kind: "embedding",
    contextWindow: 8_191,
    inputCostPerMillion: 0.13,
    outputCostPerMillion: 0,
    dimensions: 3072,
    capabilities: ["embedding"],
    status: "healthy",
    releasedAt: ago({ days: 520 }),
  },
  {
    id: "text-embedding-3-small",
    name: "text-embedding-3-small",
    providerId: "openai",
    providerName: "OpenAI",
    kind: "embedding",
    contextWindow: 8_191,
    inputCostPerMillion: 0.02,
    outputCostPerMillion: 0,
    dimensions: 1536,
    capabilities: ["embedding"],
    status: "healthy",
    releasedAt: ago({ days: 520 }),
  },
  {
    id: "claude-sonnet-4.5",
    name: "claude-sonnet-4.5",
    providerId: "anthropic",
    providerName: "Anthropic",
    kind: "chat",
    contextWindow: 200_000,
    maxOutputTokens: 64_000,
    inputCostPerMillion: 3,
    outputCostPerMillion: 15,
    capabilities: ["chat", "vision", "tools", "reasoning", "json"],
    status: "healthy",
    releasedAt: ago({ days: 62 }),
  },
  {
    id: "claude-opus-4.1",
    name: "claude-opus-4.1",
    providerId: "anthropic",
    providerName: "Anthropic",
    kind: "chat",
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    inputCostPerMillion: 15,
    outputCostPerMillion: 75,
    capabilities: ["chat", "vision", "tools", "reasoning"],
    status: "healthy",
    releasedAt: ago({ days: 88 }),
  },
  {
    id: "claude-haiku-4.5",
    name: "claude-haiku-4.5",
    providerId: "anthropic",
    providerName: "Anthropic",
    kind: "chat",
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    inputCostPerMillion: 1,
    outputCostPerMillion: 5,
    capabilities: ["chat", "tools", "json"],
    status: "healthy",
    releasedAt: ago({ days: 41 }),
  },
  {
    id: "gemini-2.5-pro",
    name: "gemini-2.5-pro",
    providerId: "google",
    providerName: "Google",
    kind: "chat",
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    inputCostPerMillion: 1.25,
    outputCostPerMillion: 10,
    capabilities: ["chat", "vision", "tools", "reasoning", "json"],
    status: "healthy",
    releasedAt: ago({ days: 132 }),
  },
  {
    id: "gemini-2.5-flash",
    name: "gemini-2.5-flash",
    providerId: "google",
    providerName: "Google",
    kind: "chat",
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    inputCostPerMillion: 0.3,
    outputCostPerMillion: 2.5,
    capabilities: ["chat", "vision", "tools", "json"],
    status: "healthy",
    releasedAt: ago({ days: 132 }),
  },
  {
    id: "text-embedding-004",
    name: "text-embedding-004",
    providerId: "google",
    providerName: "Google",
    kind: "embedding",
    contextWindow: 2_048,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
    dimensions: 768,
    capabilities: ["embedding"],
    status: "healthy",
    releasedAt: ago({ days: 610 }),
  },
  {
    id: "llama3.3-70b",
    name: "llama3.3:70b",
    providerId: "ollama",
    providerName: "Ollama",
    kind: "chat",
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
    capabilities: ["chat", "json"],
    status: "degraded",
    releasedAt: ago({ days: 290 }),
  },
  {
    id: "qwen2.5-32b",
    name: "qwen2.5:32b",
    providerId: "ollama",
    providerName: "Ollama",
    kind: "chat",
    contextWindow: 32_768,
    maxOutputTokens: 8_192,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
    capabilities: ["chat", "json"],
    status: "healthy",
    releasedAt: ago({ days: 340 }),
  },
  {
    id: "nomic-embed-text",
    name: "nomic-embed-text",
    providerId: "ollama",
    providerName: "Ollama",
    kind: "embedding",
    contextWindow: 8_192,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
    dimensions: 768,
    capabilities: ["embedding"],
    status: "healthy",
    releasedAt: ago({ days: 400 }),
  },
  {
    id: "bge-reranker-v2-m3",
    name: "bge-reranker-v2-m3",
    providerId: "ollama",
    providerName: "Ollama",
    kind: "rerank",
    contextWindow: 8_192,
    inputCostPerMillion: 0,
    outputCostPerMillion: 0,
    capabilities: ["rerank"],
    status: "healthy",
    releasedAt: ago({ days: 365 }),
  },
];

export function getProviderById(id: string): Provider | undefined {
  return mockProviders.find((provider) => provider.id === id);
}

export function getModelsByProvider(id: string): Model[] {
  return mockModels.filter((model) => model.providerId === id);
}
